{{- if .Values.apiGateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open-policy-platform.fullname" . }}-api-gateway
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "open-policy-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  replicas: {{ .Values.apiGateway.replicas }}
  selector:
    matchLabels:
      {{- include "open-policy-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api-gateway
  template:
    metadata:
      labels:
        {{- include "open-policy-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api-gateway
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api-gateway
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry }}{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}"
          imagePullPolicy: {{ .Values.apiGateway.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.apiGateway.service.port }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.apiGateway.service.port }}"
            - name: AUTH_SERVICE_URL
              value: "http://{{ include "open-policy-platform.fullname" . }}-auth-service:{{ .Values.services.authService.port }}"
            - name: CONFIG_SERVICE_URL
              value: "http://{{ include "open-policy-platform.fullname" . }}-config-service:{{ .Values.services.configService.port }}"
            - name: POLICY_SERVICE_URL
              value: "http://{{ include "open-policy-platform.fullname" . }}-policy-service:{{ .Values.services.policyService.port }}"
            - name: NOTIF_SERVICE_URL
              value: "http://{{ include "open-policy-platform.fullname" . }}-notification-service:{{ .Values.services.notificationService.port }}"
            - name: SEARCH_SERVICE_URL
              value: "http://{{ include "open-policy-platform.fullname" . }}-search-service:{{ .Values.services.searchService.port }}"
            - name: DASHBOARD_SERVICE_URL
              value: "http://{{ include "open-policy-platform.fullname" . }}-dashboard-service:{{ .Values.services.dashboardService.port }}"
            - name: LOG_LEVEL
              value: "INFO"
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.apiGateway.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-policy-platform.fullname" . }}-api-gateway
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "open-policy-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "open-policy-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
{{- end }}