apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-policy-platform.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "open-policy-platform.labels" . | nindent 4 }}
data:
  # Database Configuration
  DATABASE_URL: {{ include "open-policy-platform.databaseUrl" . | quote }}
  TEST_DATABASE_URL: {{ include "open-policy-platform.testDatabaseUrl" . | quote }}
  
  # Redis Configuration
  REDIS_URL: {{ include "open-policy-platform.redisUrl" . | quote }}
  
  # Elasticsearch Configuration
  ELASTICSEARCH_URL: {{ include "open-policy-platform.elasticsearchUrl" . | quote }}
  
  # Service URLs
  API_GATEWAY_URL: "http://{{ include "open-policy-platform.fullname" . }}-api-gateway:{{ .Values.apiGateway.service.port }}"
  
  # Logging Configuration
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  
  # Application Configuration
  APP_NAME: "OpenPolicyPlatform"
  APP_ENV: "production"
  
  # CORS Configuration
  CORS_ORIGINS: "http://{{ .Values.global.domain }},http://{{ .Values.global.adminDomain }}"
  
  # Feature Flags
  ENABLE_MONITORING: "true"
  ENABLE_TRACING: "true"
  ENABLE_METRICS: "true"