apiVersion: apps/v1
kind: Deployment
metadata:
  name: openpolicy-platform-v5
  labels:
    app: openpolicy-platform-v5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openpolicy-platform-v5
  template:
    metadata:
      labels:
        app: openpolicy-platform-v5
    spec:
      containers:
      - name: api-gateway
        image: ghcr.io/ashish-tandon/openpolicy-platform-core/api-gateway:latest
        ports:
        - containerPort: 9000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: openpolicy-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: openpolicy-secrets
              key: redis-url
        livenessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: openpolicy-platform-service
spec:
  selector:
    app: openpolicy-platform-v5
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer
