# 🚀 Production Environment Configuration (Azure)
# OpenPolicyPlatform V5 - Production Environment

environment:
  name: production
  type: azure-cloud
  description: "Production environment on Azure Cloud"
  location: "Azure Cloud"
  tier: "production"

deployment:
  method: kubernetes
  cluster: aks-openpolicy-platform
  namespace: openpolicy-platform
  replicas: 3
  auto_scaling: true
  rolling_updates: true
  health_checks: true
  backup_enabled: true
  disaster_recovery: true

infrastructure:
  resource_group: "openpolicy-platform-prod"
  vnet: "openpolicy-platform-vnet"
  subnet: "openpolicy-platform-subnet"
  load_balancer: "openpolicy-platform-lb"
  application_gateway: "openpolicy-platform-agw"
  
services:
  - name: postgres
    type: azure-postgresql-flexible
    sku: "Standard_B2s"
    storage: "32GB"
    backup_retention: "35 days"
    geo_redundant: true
    
  - name: redis
    type: azure-redis-cache
    sku: "Standard_C1"
    capacity: 1
    enable_non_ssl_port: false
    
  - name: elasticsearch
    type: azure-elasticsearch
    sku: "Standard_E2s_v3"
    storage: "100GB"
    
  - name: storage
    type: azure-storage-account
    sku: "Standard_LRS"
    tier: "Hot"
    access_tier: "Hot"

monitoring:
  log_level: WARNING
  metrics_enabled: true
  alerting: true
  alert_channels:
    - email: "ops@company.com"
    - slack: "#production-alerts"
    - pagerduty: "openpolicy-platform"
    - teams: "OpenPolicy Platform Ops"
  
  azure_monitor:
    application_insights: true
    log_analytics: true
    alert_rules: true
    dashboards: true
    
  sla_targets:
    uptime: "99.9%"
    response_time: "<200ms"
    error_rate: "<0.1%"

security:
  ssl_enabled: true
  auth_required: true
  cors_enabled: true
  msi_enabled: true
  key_vault: "openpolicy-platform-kv"
  
  network_security:
    private_endpoints: true
    service_endpoints: true
    firewall_rules: true
    ddos_protection: true
    
  compliance:
    iso_27001: true
    soc_2: true
    gdpr: true
    hipaa: true

backup:
  frequency: "hourly"
  retention: "90 days"
  geo_redundant: true
  point_in_time_restore: true
  
disaster_recovery:
  rto: "<4 hours"
  rpo: "<1 hour"
  multi_region: true
  failover_automation: true
