# ========================================
# LOCAL DEVELOPMENT ENVIRONMENT VALUES
# ========================================
# This file overrides default values for local development

global:
  environment: "local"
  imageRegistry: "localhost:5000"
  domain: "localhost"
  adminDomain: "localhost"

# Local development - minimal resources
infrastructure:
  postgres:
    persistence:
      size: 5Gi
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m
  
  postgresTest:
    persistence:
      size: 2Gi
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m
  
  redis:
    persistence:
      size: 1Gi
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  elasticsearch:
    persistence:
      size: 10Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 2Gi
        cpu: 1000m
  
  logstash:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m
  
  kibana:
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m
  
  prometheus:
    persistence:
      size: 2Gi
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m
  
  grafana:
    persistence:
      size: 1Gi
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  fluentd:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m

# Local development - single replicas
microservices:
  apiGateway:
    replicaCount: 1
    service:
      type: NodePort
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  configService:
    replicaCount: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  authService:
    replicaCount: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  policyService:
    replicaCount: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  notificationService:
    replicaCount: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  analyticsService:
    replicaCount: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  monitoringService:
    replicaCount: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  etlService:
    replicaCount: 1
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m
  
  scraperService:
    replicaCount: 1
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m
  
  searchService:
    replicaCount: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  dashboardService:
    replicaCount: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  filesService:
    replicaCount: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  reportingService:
    replicaCount: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  workflowService:
    replicaCount: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  integrationService:
    replicaCount: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  dataManagementService:
    replicaCount: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  representativesService:
    replicaCount: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  plotlyService:
    replicaCount: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  mobileApi:
    replicaCount: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  legacyDjango:
    replicaCount: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
  
  web:
    replicaCount: 1
    service:
      type: NodePort
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m

# Local development - no ingress
microservices.apiGateway.ingress.enabled = false
microservices.web.ingress.enabled = false

# Local development - simplified monitoring
monitoring:
  healthChecks:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  
  readinessProbes:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  
  livenessProbes:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

# Local development - no HPA
hpa:
  enabled: false

# Local development - simplified security
podSecurityContext:
  fsGroup: 1000
  runAsNonRoot: false
  runAsUser: 1000

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 1000
  capabilities:
    drop: []
