apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-api
  namespace: openpolicy
  labels:
    app: mobile-api
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mobile-api
  template:
    metadata:
      labels:
        app: mobile-api
        tier: api
    spec:
      containers:
      - name: mobile-api
        image: mobile-api:latest
        ports:
        - containerPort: 8009
        env:
        - name: PORT
          value: "8009"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8009
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8009
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mobile-api-service
  namespace: openpolicy
  labels:
    app: mobile-api
    tier: api
spec:
  type: ClusterIP
  ports:
  - port: 8009
    targetPort: 8009
    protocol: TCP
    name: http
  selector:
    app: mobile-api